--- #YAML:1.0
name: Bot-BasicBot-Pluggable-Module-Assemble
version: 0.01
author:
  - Philippe "BooK" Bruhat <book@cpan.org>
abstract: IRC frontend to Regexp::Assemble
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
